# Generated by Django 4.0.1 on 2022-01-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=155, unique=True)),
                ('published_date', models.CharField(blank=True, max_length=50, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ratings_count', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='books.Author')),
                ('categories', models.ManyToManyField(blank=True, to='books.Category')),
            ],
        ),
    ]
