# Generated by Django 4.0.1 on 2022-01-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_publication_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_link',
        ),
        migrations.AddField(
            model_name='book',
            name='book_link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
