# Generated by Django 4.0.1 on 2022-01-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_book_link_book_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='publication_year',
        ),
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
