# Generated by Django 4.0.1 on 2022-02-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_author_category_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(default=None, max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_language',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
