# Generated by Django 4.0.1 on 2022-02-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
