# Generated by Django 4.0.1 on 2022-02-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_language',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
